export const alias = {
  id: 'id',
  className: 'class',
  style: 'style',
  scrollX: 'scroll-x',
  scrollY: 'scroll-y',
  upperThreshold: 'upper-threshold',
  lowerThreshold: 'lower-threshold',
  scrollTop: 'scroll-top',
  scrollLeft: 'scroll-left',
  scrollIntoView: 'scroll-into-view',
  scrollWithAnimation: 'scroll-with-animation',
  refresherEnabled: 'refresher-enabled',
  refresherDefaultStyle: 'refresher-default-style',
  refresherBackground: 'refresher-background',
  refresherThreshold: 'refresher-threshold',
  refresherTriggered: 'refresher-triggered',
  enhanced: 'enhanced',
  bounces: 'bounces',
  onScrollToUpper: 'bindscrolltoupper',
  onScrollToLower: 'bindscrolltolower',
  onScroll: 'bindscroll',
  onRefresherPulling: 'bindrefresherpulling',
  onRefresherRefresh: 'bindrefresherrefresh',
  onRefresherRestore: 'bindrefresherrestore',
  onRefresherAbort: 'bindrefresherabort',
  onTap: 'bindtap',
  onClick: 'bindtap',
  animation: 'animation',
};

export const props = Object.values(alias);
