import * as ad from './Ad/node';
import * as button from './Button/node';
import * as camera from './Camera/node';
import * as canvas from './Canvas/node';
import * as checkbox from './Checkbox/node';
import * as checkboxGroup from './CheckboxGroup/node';
import * as form from './Form/node';
import * as icon from './Icon/node';
import * as image from './Image/node';
import * as input from './Input/node';
import * as label from './Label/node';
import * as livePlayer from './LivePlayer/node';
import * as livePreview from './LivePreview/node';
import * as map from './Map/node';
import * as openData from './OpenData/node';
import * as awemeData from './AwemeData/node';
import * as mask from './Mask/node';
import * as matchMedia from './MatchMedia/node';
import * as movableArea from './MovableArea/node';
import * as movableView from './MovableView/node';
import * as navigator from './Navigator/node';
import * as picker from './Picker/node';
import * as pickerView from './PickerView/node';
import * as pickerViewColumn from './PickerViewColumn/node';
import * as progress from './Progress/node';
import * as radio from './Radio/node';
import * as radioGroup from './RadioGroup/node';
import * as richText from './RichText/node';
import * as rtcRoom from './RtcRoom/node';
import * as scrollView from './ScrollView/node';
import * as slider from './Slider/node';
import * as swiper from './Swiper/node';
import * as swiperItem from './SwiperItem/node';
import * as switchComponent from './Switch/node';
import * as text from './Text/node';
import * as textarea from './Textarea/node';
import * as video from './Video/node';
import * as view from './View/node';
import * as webView from './WebView/node';
import * as drawAd from './DrawAd/node';
import * as awemeUserCard from './AwemeUserCard/node';
import * as payButton from './PayButton/node';
import * as payButtonSdk from './PayButtonSdk/node';
import * as consumeCard from './ConsumeCard/node';
import * as paymentChannelSelect from './PaymentChannelSelect/node';
import * as rateButton from './RateButton/node';
import * as skuButton from './SkuButton/node';
import * as productFollowButton from './ProductFollowButton/node';
import * as shopFollowCard from './ShopFollowCard/node';
import * as industryMemberButton from './IndustryMemberButton/node';
import * as couponCard from './CouponCard/node';
import * as memberButton from './MemberButton/node';

const hostComponents = new Map();

hostComponents.set('button', button);
hostComponents.set('canvas', canvas);
hostComponents.set('checkbox-group', checkboxGroup);
hostComponents.set('checkbox', checkbox);
hostComponents.set('form', form);
hostComponents.set('icon', icon);
hostComponents.set('image', image);
hostComponents.set('input', input);
hostComponents.set('label', label);
hostComponents.set('navigator', navigator);
hostComponents.set('picker-view-column', pickerViewColumn);
hostComponents.set('picker-view', pickerView);
hostComponents.set('picker', picker);
hostComponents.set('progress', progress);
hostComponents.set('radio-group', radioGroup);
hostComponents.set('radio', radio);
hostComponents.set('rich-text', richText);
hostComponents.set('scroll-view', scrollView);
hostComponents.set('slider', slider);
hostComponents.set('swiper-item', swiperItem);
hostComponents.set('swiper', swiper);
hostComponents.set('switch', switchComponent);
hostComponents.set('text', text);
hostComponents.set('textarea', textarea);
hostComponents.set('video', video);
hostComponents.set('view', view);
hostComponents.set('web-view', webView);
hostComponents.set('movable-area', movableArea);
hostComponents.set('movable-view', movableView);
hostComponents.set('mask', mask);
hostComponents.set('ad', ad);
hostComponents.set('rtc-room', rtcRoom);
hostComponents.set('match-media', matchMedia);
hostComponents.set('live-player', livePlayer);
hostComponents.set('live-preview', livePreview);
hostComponents.set('camera', camera);
hostComponents.set('map', map);
hostComponents.set('open-data', openData);
hostComponents.set('aweme-data', awemeData);
hostComponents.set('draw-ad', drawAd);
hostComponents.set('aweme-user-card', awemeUserCard);
hostComponents.set('pay-button', payButton);
hostComponents.set('pay-button-sdk', payButtonSdk);
hostComponents.set('consume-card', consumeCard);
hostComponents.set('payment-channel-select', paymentChannelSelect);
hostComponents.set('rate-button', rateButton);
hostComponents.set('sku-button', skuButton);
hostComponents.set('product-follow-button', productFollowButton);
hostComponents.set('shop-follow-card', shopFollowCard);
hostComponents.set('industry-member-button', industryMemberButton);
hostComponents.set('coupon-card', couponCard);
hostComponents.set('member-button', memberButton);

export default hostComponents;
