export const alias = {
  id: 'id',
  className: 'class',
  style: 'style',
  animation: 'animation',
  show: 'show',
  duration: 'duration',
  zIndex: 'z-index',
  overlay: 'overlay',
  position: 'position',
  round: 'round',
  closeOnSlideDown: 'close-on-slide-down',
  overlayStyle: 'overlay-style',
  customStyle: 'custom-style',
  onBeforeEnter: 'bindbeforeenter',
  onEnter: 'bindenter',
  onAfterEnter: 'bindafterenter',
  onBeforeLeave: 'bindbeforeleave',
  onLeave: 'bindleave',
  onAfterLeave: 'bindafterleave',
  onClickOverlay: 'bindclickoverlay',
};
export const props = Object.values(alias);
