export const alias = {
  longitude: 'longitude',
  latitude: 'latitude',
  scale: 'scale',
  markers: 'markers',
  circles: 'circles',
  showLocation: 'show-location',
  polyline: 'polyline',
  includePoints: 'include-points',
  onTap: 'bindtap',
  onClick: 'bindtap',
  onMarkerTap: 'bindmarkertap',
  onCalloutTap: 'bindcallouttap',
  onRegionChange: 'bindregionchange',
  rotate: 'rotate',
  skew: 'skew',
  polygons: 'polygons',
  showCompass: 'show-compass',
  enableOverlooking: 'enable-overlooking',
  enableRotate: 'enable-rotate',
  minScale: 'min-scale',
  maxScale: 'max-scale',
  enable3D: 'enable-3D',
  showScale: 'show-scale',
  enableZoom: 'enable-zoom',
  enableScroll: 'enable-scroll',
  enableSatellite: 'enable-satellite',
  enableTraffic: 'enable-traffic',
  enablePoi: 'enable-poi',
  enableBuilding: 'enable-building',
  onLabelTap: 'bindlabeltap',
  onUpdated: 'bindupdated',
  onAnchorPointTap: 'bindanchorpointtap',
};

export const props = Object.values(alias);
