name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [ 18,20 ]
    steps:
      - uses: actions/checkout@v4
      - name: Install Pnpm
        run: |
          npm install -g corepack@latest --force
          corepack enable
      - name: 使用 Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: install, build, and test
        run: |
          pnpm install --force-lockfile
          pnpm build
          pnpm test

